### ISSUE TITLE
Advanced tools update

### ISSUE THREAD

**Issue by nick-traveltime** [traveltime-dev/traveltime-platform-qgis-plugin#38]
- Advanced tools to match the simplified tools so you can just select 'departure' or 'arrivals' from a dynamic field without both being visible.
- Change the time value from seconds to minutes
- Also an addition of a field for timezone

**Comment by olivierdalang** [comment]
About this : with exception for the new field for timezone, this will break backwards compatibility. This means that any existing workflow would fail and/or return wrong results.

Are the changes worth that ?

Conceptually, the idea was to have the advanced algorithm match the API as closely as possible, so that advanced users can leverage most features of the API. Users that don't want to dig too deep in the API should rather use the express tools, or the simple algorithms.

**Comment by olivierdalang** [comment]
Also, for the timezone, it could get a bit complicated too, as as dates are using ISO 8601 (e.g. `2021-06-16T22:00:00+02:00` for GMT +2) which would be ambiguous if we also have a timezone input.

All in all, I'd suggest to not do those changes, and redirect users to the simple/express tools if they like it simple, as to avoid breaking user's workflows.

I also don't like the idea of adding yet another "intermediate" version of the algorithm (which would allow to both keep existing workflows, yet also add a new version with the desired changes) as it would start to be a bit complex to document/understand.

If you still want the changes, we could change the ID of the algorithms, so that at least existing workflows would completely fail instead of silently returning different values. You'd also have to clearly communicate the change to all users you know of. Unfortunately, besides the changelog that is not very visible, there is no way to warn the users that upgrading the plugin will break their workflows.

Let me know what you think.

**Comment by nick-traveltime** [comment]
Hi Olivier - sorry for the long response time. 

I understand what you are saying about the advanced algorithms and thoughts about changing it. So have a couple of proposals mainly concerned with UX improvements.

1. Could we instead add a 'fields to keep' function to the simplified tools - this should hopefully add better functionality to the tool for users.
2. My main change I wanted with the advanced was more centered around UX and how the departures/arrivals searches are close together that it looks like you need to add all values in. Could we, maybe instead of a dynamic drop down field to select the option if its too complicated, just add some spaces between departures and arrivals? I think this may help the UX of understanding only one field needs to be filled in.

Thanks

**Comment by olivierdalang** [comment]
Ok for 1.

For 2, it's theoretically possible to add a custom UI to algorithm, but it has drawbacks : it does not apply when running as a batch process, and also adds some more maintenance burden in the long term.

An alternative could be to add 2 more variants of each advanced algorithm that only provide departure or arrival fields, which also applies when running in batch.

![image](https://user-images.githubusercontent.com/1894106/126792803-eae3cc34-2530-41f1-9d86-5e29b857fd57.png)

I've a PR ready with that already.

What do you think ?

**Comment by nick-traveltime** [comment]
Hi Olivier,

Thanks for confirming changes to point 1.

For point 2 - I will be honest, I don't think the addition of more options by arrival and departure will be suitable. Could we investigate just adding some blank spaces between the arrivals and departures so that users can more easily differentiate between the two?

**Comment by olivierdalang** [comment]
Ok here's a last proposal before going for a custom UI (which I'd as much as possible like to avoid mostly for long term maintenance burden) :

![image](https://user-images.githubusercontent.com/1894106/130432391-31ee04a6-3b6a-43cd-b5e5-86d44e23abe5.png)

The only drawback of that is that it relies on a hack (using HTML in the parameter's label), which doesn't look good in other contexts such as batch run dialog)

Is this ok for you ?

**Comment by nick-traveltime** [comment]
This is great thanks Olivier, would be good to test out if possible before release?

Thanks

**Comment by olivierdalang** [comment]
(forgot to close that a while ago)
