### ISSUE TITLE
API throttle

### ISSUE THREAD

**Issue by nick-traveltime** [traveltime-dev/traveltime-platform-qgis-plugin#39]
A throttle to allow a maximum of 300 requests per minute. If possible a selectable function in the settings bar

**Comment by olivierdalang** [comment]
Hi !

Are there other limitations besides the 300/minutes (such as quota per month) ?
Do all API keys have the same quota limits, or are there things like demo or pro accounts with lower/higher quotas ?

I'm asking because alternatively to checking this client-side only, we could imagine an API endpoint to retrieve the current quota for the current user, that would be more reliable and more future-proof (but requires API changes).

**Comment by nick-traveltime** [comment]
Hi Olivier!

I'm currently running past the team internally, I think it may certainly be possible and after running it by Charlie, he thinks it would be a great idea. I'll get back to you on this.

Thanks

**Comment by nick-traveltime** [comment]
Hi Olivier - while we may look to implement an API level throttler in the future, we would still like to have one now and changeable on QGIS itself. So if we can proceed with one potentially within the settings bar, that would be great!

Thanks

**Comment by olivierdalang** [comment]
@nick-traveltime I've done a first implementation (in master).

One small drawback is that except messages in the log, it's not easy to display nice visual feedback (such as a progress bar or hourglass), because we use the QGIS processing framework that must also work headless.

Are you able to test to see if implementation is fine, or if more effort in user feedback is needed ?

Also can you please specify if you want this feature enabled or not by default ?

![image](https://user-images.githubusercontent.com/1894106/122286720-711b0080-cef0-11eb-8c37-aa9ad475cd5e.png)

**Comment by olivierdalang** [comment]
Made the changes discussed on slack.

Open questions :
- [ ] Do we want throttling enabled by default ? (currently, not enabled by default)
- [ ] How are geocoding queries counted ? currently, it is counted as 1 search per query, but maybe it counts differently ?
- [ ] Thinking of it again, it may be better to be able to toggle the throttling option as an algorithm input rather than a global setting, and to NOT use it by default with quick map tools, as then, the behaviour is a surprising (you click, and think it does not work, then get the results 30s later, maybe after having already clicked several other times - much better to simply show an error, then the user knows he must wait and try again a bit later).

**Comment by nick-traveltime** [comment]
Hi Olivier - thanks!

Can we please go with the following, I think it will be better for UX

- Throttling not enabled by default as suggested
- Geocoding is counted as 1 search per query - though we have no restrictions on it
- I would prefer to keep this in the settings so it can be turned on and off. However, could we please not have it enable for the quick tools (as you suggest) as well as geocoding?

Essentially if the throttle stays where it is and only is used for the simplified and advanced tools, that would be great.

**Comment by olivierdalang** [comment]
Ok done. To allow disabling of throttling with express tools, I had to add an advanced "THROTTLING_STRATEGY" param for the advanced algorithm, which allows to choose whether throttling settings are used or force disabling throttling.
