### ISSUE TITLE
Time Map UNION not returning shapes in some cases

### ISSUE THREAD

**Issue by chris-traveltime** [traveltime-dev/traveltime-platform-qgis-plugin#46]
Sometimes when running either Time Map Simple or Time Map Advanced, with the Output style as UNION, the tool runs and creates an output layer, but nothing is displayed on the map.

It seems to happen at certain travel times, depending on the mode of transport. 

For example, with the attached layer, the following parameters don't return a result:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/72020226/159698836-87b89591-252a-4b7f-bd8c-dd7f7759a221.png">

But the same parameters with a travel time of 15 mins or 120 mins do return a shape.

[UNION_Error_data.zip](https://github.com/traveltime-dev/traveltime-platform-qgis-plugin/files/8332976/UNION_Error_data.zip)

**Comment by olivierdalang** [comment]
@chris-traveltime I just tested, here I do get results.

Can you try again, and if the problem persists:
- make sure your cleared the cache (otherwise, you could be reusing 24h-old locally cached results)
- make sure the "log API calls" checkbox is checked
- attach the processing log (processing window)
- attach the content of the QGIS logs (TravelTime tab and Processing in the log messages panel)
- attach the content of the QGIS about dialog (showing detailed info about the QGIS version)

![image](https://user-images.githubusercontent.com/1894106/160377197-854f435c-f56f-45c2-b083-af66383112fb.png)
