### ISSUE TITLE
Possible workaround for QGIS Master Password Authentication?

### ISSUE THREAD

**Issue by chris-traveltime** [traveltime-dev/traveltime-platform-qgis-plugin#50]
Running any of the tools requires the QGIS Master Password Authentication to be set. But if this isn't set before running a toolbox tool, it causes QGIS to crash.

**Comment by olivierdalang** [comment]
I investigated on this, I think this is due to an upstream bug that is not really fixable in the plugin. Here's the upstream bug report : https://github.com/qgis/QGIS/issues/51317

As a workaround, I added a check in the algorithm so that we get a clean error instead of a crash. The error indicates that the user should open the plugin configuration, which as side effect will prompt the user to create/enter a master password.

The day the above issue is fixed, we can revert that check, so that the user can just provide the master password when running the algorithm.

**Comment by olivierdalang** [comment]
Found a better way to do it, fixed here : https://github.com/traveltime-dev/traveltime-platform-qgis-plugin/pull/66
